spring:
  application:
    name: Reminder
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/reminder}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
