spring:
  application:
    name: Reminder
  datasource:
    url: jdbc:postgresql://localhost:5432/reminder
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

